# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-02-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210206_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='contract_agreed',
            field=models.BooleanField(default=True, verbose_name='我已认真阅读完培训协议并同意全部协议内容'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='contract_approved',
            field=models.BooleanField(default=False, help_text='在审阅完学员的资料无误后勾选此项,合同即生效', verbose_name='审批通过'),
        ),
    ]
